### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pratyaysaha** [kaimallea/node-imgur#219] opened 2021-09-10 06:45 UTC
**Describe the bug**
This appears when I try to upload a base64 encoded image via multer dependency in NodeJS.

**To Reproduce**
```javascript
exports.createPost = async (req, res) => {
	console.log(req.file)
	console.log(req.body)
	try {
		const imageUpload = await client.upload({
			image: req.file.buffer.toString("base64"),
			name: req.file.originalname,
			title: req.body.title,
			type: "base64",
		})
		console.log(imageUpload)
	} catch (err) {
		console.log(err)
	}
} 
```

**Expected behavior**
The expected behaviour should have been a proper 200 OK response with the JSON object returning the information.

**Screenshots**
![image](https://user-images.githubusercontent.com/14862155/132811377-f332632e-e4c1-4c00-89c2-ff2d0c446bd0.png)

**Environment (please complete the following information):**
 - Library version [e.g. 1.0.0]: `imgur@next`
 - OS [e.g. macOS]: `windows10`
 - NodeJS version [e.g.14.16.0]: `14.16.0`

**Additional context**
Well, I found a resolved issue in v1 which was then resolved.
But this one seems to e the same issue with v2.

**Comment by Acituanbus** [comment] 2021-09-11 19:33
Same issue here, I'm unable to upload buffers :/

**Comment by Pulau-Komodo** [comment] 2021-09-13 14:25
It seems to me the problem is here: https://github.com/kaimallea/node-imgur/blob/1b2c55d5d3fb7db715e39303401f2328ba909d37/src/common/utils.ts#L34-L39

If the key is "image" or "video", and the payload is not falsey or "file", the key and value are discarded entirely, which seems unintended.

**Comment by ProfessorVarox** [comment] 2021-09-26 12:34
Same issue when trying to upload using `type: "url"`

**Comment by KenEucker** [comment] 2021-12-17 04:32
All, I am sorry that you haven't received a reply to this issue.

This package is now being maintained in another repository: https://github.com/KenEucker/imgur and the new version might have already addressed your concerns.

imgur@v2 will be released before the end of 2021, and with that will come a couple of breaking changes -> **dropping support for filesystem uploads** which means you have to create your streams on your own and pass them to the API.

Please come help us maintain v2!

**Closed** 2021-12-17 04:31 UTC
Labels: Bug
